/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('./components/subLayout/Accordion.vue')['default']
    Epic: typeof import('./components/types/Epic.vue')['default']
    Field: typeof import('./components/subLayout/input/Field.vue')['default']
    Form: typeof import('./components/form/index.vue')['default']
    Input: typeof import('./components/subLayout/input/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Row: typeof import('./components/form/Row.vue')['default']
    Selects: typeof import('./components/types/Selects.vue')['default']
    Tabs: typeof import('./components/subLayout/Tabs.vue')['default']
    TextArea: typeof import('./components/types/TextArea.vue')['default']
    TextField: typeof import('./components/types/TextField.vue')['default']
  }
}
