/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('./components/subLayout/Accordion.vue')['default']
    Breeze: typeof import('./components/theme/Breeze.vue')['default']
    Card: typeof import('./components/theme/Card.vue')['default']
    CheckBoxes: typeof import('./components/types/CheckBoxes.vue')['default']
    Datepicker: typeof import('./components/types/Datepicker.vue')['default']
    DateTimePicker: typeof import('./components/types/DateTimePicker.vue')['default']
    Epic: typeof import('./components/types/Epic.vue')['default']
    Field: typeof import('./components/subLayout/input/Field.vue')['default']
    FileInput: typeof import('./components/types/FileInput.vue')['default']
    Fluid: typeof import('./components/theme/Fluid.vue')['default']
    Form: typeof import('./components/form/index.vue')['default']
    Input: typeof import('./components/subLayout/input/index.vue')['default']
    Map: typeof import('./components/dynamic/Map.vue')['default']
    Password: typeof import('./components/types/Password.vue')['default']
    Plain: typeof import('./components/theme/Plain.vue')['default']
    Pop: typeof import('./components/dynamic/Pop.vue')['default']
    RadioButtons: typeof import('./components/types/RadioButtons.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Row: typeof import('./components/form/Row.vue')['default']
    Selects: typeof import('./components/types/Selects.vue')['default']
    Single: typeof import('./components/fileInput/Single.vue')['default']
    Slider: typeof import('./components/fileInput/Slider.vue')['default']
    Tabs: typeof import('./components/subLayout/Tabs.vue')['default']
    TextArea: typeof import('./components/types/TextArea.vue')['default']
    TextField: typeof import('./components/types/TextField.vue')['default']
  }
}
