/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ExamplesDynamicAlias: typeof import('./components/examples/dynamic/alias/index.vue')['default']
    ExamplesDynamicAliasTranslationsDialog: typeof import('./components/examples/dynamic/alias/TranslationsDialog.vue')['default']
    ExamplesDynamicMap: typeof import('./components/examples/dynamic/Map.vue')['default']
    FileUploadDialogUpload: typeof import('./components/fileUpload/DialogUpload.vue')['default']
    FileUploadGallery: typeof import('./components/fileUpload/gallery/index.vue')['default']
    FileUploadGalleryThumbnail: typeof import('./components/fileUpload/gallery/Thumbnail.vue')['default']
    FileUploadToolbar: typeof import('./components/fileUpload/Toolbar.vue')['default']
    Form: typeof import('./components/form/index.vue')['default']
    FormRow: typeof import('./components/form/Row.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubLayoutAccordion: typeof import('./components/subLayout/Accordion.vue')['default']
    SubLayoutInput: typeof import('./components/subLayout/input/index.vue')['default']
    SubLayoutInputErrors: typeof import('./components/subLayout/input/errors/index.vue')['default']
    SubLayoutInputErrorsItem: typeof import('./components/subLayout/input/errors/Item.vue')['default']
    SubLayoutInputField: typeof import('./components/subLayout/input/Field.vue')['default']
    SubLayoutInputGroups: typeof import('./components/subLayout/inputGroups/index.vue')['default']
    SubLayoutInputGroupsRenderItem: typeof import('./components/subLayout/inputGroups/RenderItem.vue')['default']
    SubLayoutTabs: typeof import('./components/subLayout/Tabs.vue')['default']
    ThemeBreeze: typeof import('./components/theme/Breeze.vue')['default']
    ThemeCard: typeof import('./components/theme/Card.vue')['default']
    ThemeFluid: typeof import('./components/theme/Fluid.vue')['default']
    ThemePlain: typeof import('./components/theme/Plain.vue')['default']
    TypesAutocomplete: typeof import('./components/types/Autocomplete.vue')['default']
    TypesCheckBoxes: typeof import('./components/types/CheckBoxes.vue')['default']
    TypesCombobox: typeof import('./components/types/Combobox.vue')['default']
    TypesDatepicker: typeof import('./components/types/Datepicker.vue')['default']
    TypesDateTimePicker: typeof import('./components/types/DateTimePicker.vue')['default']
    TypesDynamic: typeof import('./components/types/dynamic.vue')['default']
    TypesEpic: typeof import('./components/types/Epic.vue')['default']
    TypesFileInput: typeof import('./components/types/FileInput.vue')['default']
    TypesFileUpload: typeof import('./components/types/FileUpload.vue')['default']
    TypesNumberInput: typeof import('./components/types/NumberInput.vue')['default']
    TypesPassword: typeof import('./components/types/Password.vue')['default']
    TypesRadioButtons: typeof import('./components/types/RadioButtons.vue')['default']
    TypesSelects: typeof import('./components/types/Selects.vue')['default']
    TypesSwitch: typeof import('./components/types/Switch.vue')['default']
    TypesTextArea: typeof import('./components/types/TextArea.vue')['default']
    TypesTextField: typeof import('./components/types/TextField.vue')['default']
  }
}
