/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/diagrams': RouteRecordInfo<'/diagrams', '/diagrams', Record<never, never>, Record<never, never>>,
    '/examples/': RouteRecordInfo<'/examples/', '/examples', Record<never, never>, Record<never, never>>,
    '/examples/accordion': RouteRecordInfo<'/examples/accordion', '/examples/accordion', Record<never, never>, Record<never, never>>,
    '/examples/checks-radios': RouteRecordInfo<'/examples/checks-radios', '/examples/checks-radios', Record<never, never>, Record<never, never>>,
    '/examples/conditionals': RouteRecordInfo<'/examples/conditionals', '/examples/conditionals', Record<never, never>, Record<never, never>>,
    '/examples/contactForm': RouteRecordInfo<'/examples/contactForm', '/examples/contactForm', Record<never, never>, Record<never, never>>,
    '/examples/datepicker': RouteRecordInfo<'/examples/datepicker', '/examples/datepicker', Record<never, never>, Record<never, never>>,
    '/examples/dynamicComponents': RouteRecordInfo<'/examples/dynamicComponents', '/examples/dynamicComponents', Record<never, never>, Record<never, never>>,
    '/examples/epic': RouteRecordInfo<'/examples/epic', '/examples/epic', Record<never, never>, Record<never, never>>,
    '/examples/fileInput': RouteRecordInfo<'/examples/fileInput', '/examples/fileInput', Record<never, never>, Record<never, never>>,
    '/examples/password': RouteRecordInfo<'/examples/password', '/examples/password', Record<never, never>, Record<never, never>>,
    '/examples/slots': RouteRecordInfo<'/examples/slots', '/examples/slots', Record<never, never>, Record<never, never>>,
    '/examples/tabs': RouteRecordInfo<'/examples/tabs', '/examples/tabs', Record<never, never>, Record<never, never>>,
    '/examples/themes/Breeze': RouteRecordInfo<'/examples/themes/Breeze', '/examples/themes/Breeze', Record<never, never>, Record<never, never>>,
    '/examples/themes/Fluid': RouteRecordInfo<'/examples/themes/Fluid', '/examples/themes/Fluid', Record<never, never>, Record<never, never>>,
    '/oldExamples/': RouteRecordInfo<'/oldExamples/', '/oldExamples', Record<never, never>, Record<never, never>>,
    '/oldExamples/accordion': RouteRecordInfo<'/oldExamples/accordion', '/oldExamples/accordion', Record<never, never>, Record<never, never>>,
    '/oldExamples/checks-radios': RouteRecordInfo<'/oldExamples/checks-radios', '/oldExamples/checks-radios', Record<never, never>, Record<never, never>>,
    '/oldExamples/conditionals': RouteRecordInfo<'/oldExamples/conditionals', '/oldExamples/conditionals', Record<never, never>, Record<never, never>>,
    '/oldExamples/contactForm': RouteRecordInfo<'/oldExamples/contactForm', '/oldExamples/contactForm', Record<never, never>, Record<never, never>>,
    '/oldExamples/datepicker': RouteRecordInfo<'/oldExamples/datepicker', '/oldExamples/datepicker', Record<never, never>, Record<never, never>>,
    '/oldExamples/dynamicComponents': RouteRecordInfo<'/oldExamples/dynamicComponents', '/oldExamples/dynamicComponents', Record<never, never>, Record<never, never>>,
    '/oldExamples/epic': RouteRecordInfo<'/oldExamples/epic', '/oldExamples/epic', Record<never, never>, Record<never, never>>,
    '/oldExamples/fileInput': RouteRecordInfo<'/oldExamples/fileInput', '/oldExamples/fileInput', Record<never, never>, Record<never, never>>,
    '/oldExamples/password': RouteRecordInfo<'/oldExamples/password', '/oldExamples/password', Record<never, never>, Record<never, never>>,
    '/oldExamples/slots': RouteRecordInfo<'/oldExamples/slots', '/oldExamples/slots', Record<never, never>, Record<never, never>>,
    '/oldExamples/tabs': RouteRecordInfo<'/oldExamples/tabs', '/oldExamples/tabs', Record<never, never>, Record<never, never>>,
    '/oldExamples/themes/Breeze': RouteRecordInfo<'/oldExamples/themes/Breeze', '/oldExamples/themes/Breeze', Record<never, never>, Record<never, never>>,
    '/oldExamples/themes/Fluid': RouteRecordInfo<'/oldExamples/themes/Fluid', '/oldExamples/themes/Fluid', Record<never, never>, Record<never, never>>,
  }
}
