/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/devExamples/': RouteRecordInfo<'/devExamples/', '/devExamples', Record<never, never>, Record<never, never>>,
    '/devExamples/accordion': RouteRecordInfo<'/devExamples/accordion', '/devExamples/accordion', Record<never, never>, Record<never, never>>,
    '/devExamples/checks-radios': RouteRecordInfo<'/devExamples/checks-radios', '/devExamples/checks-radios', Record<never, never>, Record<never, never>>,
    '/devExamples/conditionals': RouteRecordInfo<'/devExamples/conditionals', '/devExamples/conditionals', Record<never, never>, Record<never, never>>,
    '/devExamples/contactForm': RouteRecordInfo<'/devExamples/contactForm', '/devExamples/contactForm', Record<never, never>, Record<never, never>>,
    '/devExamples/datepicker': RouteRecordInfo<'/devExamples/datepicker', '/devExamples/datepicker', Record<never, never>, Record<never, never>>,
    '/devExamples/dynamicComponents': RouteRecordInfo<'/devExamples/dynamicComponents', '/devExamples/dynamicComponents', Record<never, never>, Record<never, never>>,
    '/devExamples/epic': RouteRecordInfo<'/devExamples/epic', '/devExamples/epic', Record<never, never>, Record<never, never>>,
    '/devExamples/fileInput': RouteRecordInfo<'/devExamples/fileInput', '/devExamples/fileInput', Record<never, never>, Record<never, never>>,
    '/devExamples/password': RouteRecordInfo<'/devExamples/password', '/devExamples/password', Record<never, never>, Record<never, never>>,
    '/devExamples/readonly': RouteRecordInfo<'/devExamples/readonly', '/devExamples/readonly', Record<never, never>, Record<never, never>>,
    '/devExamples/slots': RouteRecordInfo<'/devExamples/slots', '/devExamples/slots', Record<never, never>, Record<never, never>>,
    '/devExamples/tabs': RouteRecordInfo<'/devExamples/tabs', '/devExamples/tabs', Record<never, never>, Record<never, never>>,
    '/devExamples/themes/Breeze': RouteRecordInfo<'/devExamples/themes/Breeze', '/devExamples/themes/Breeze', Record<never, never>, Record<never, never>>,
    '/devExamples/themes/Fluid': RouteRecordInfo<'/devExamples/themes/Fluid', '/devExamples/themes/Fluid', Record<never, never>, Record<never, never>>,
    '/diagrams': RouteRecordInfo<'/diagrams', '/diagrams', Record<never, never>, Record<never, never>>,
    '/examples/': RouteRecordInfo<'/examples/', '/examples', Record<never, never>, Record<never, never>>,
    '/examples/accordion': RouteRecordInfo<'/examples/accordion', '/examples/accordion', Record<never, never>, Record<never, never>>,
    '/examples/checks-radios': RouteRecordInfo<'/examples/checks-radios', '/examples/checks-radios', Record<never, never>, Record<never, never>>,
    '/examples/conditionals': RouteRecordInfo<'/examples/conditionals', '/examples/conditionals', Record<never, never>, Record<never, never>>,
    '/examples/contactForm': RouteRecordInfo<'/examples/contactForm', '/examples/contactForm', Record<never, never>, Record<never, never>>,
    '/examples/datepicker': RouteRecordInfo<'/examples/datepicker', '/examples/datepicker', Record<never, never>, Record<never, never>>,
    '/examples/dynamicComponents': RouteRecordInfo<'/examples/dynamicComponents', '/examples/dynamicComponents', Record<never, never>, Record<never, never>>,
    '/examples/epic': RouteRecordInfo<'/examples/epic', '/examples/epic', Record<never, never>, Record<never, never>>,
    '/examples/fileInput': RouteRecordInfo<'/examples/fileInput', '/examples/fileInput', Record<never, never>, Record<never, never>>,
    '/examples/password': RouteRecordInfo<'/examples/password', '/examples/password', Record<never, never>, Record<never, never>>,
    '/examples/slots': RouteRecordInfo<'/examples/slots', '/examples/slots', Record<never, never>, Record<never, never>>,
    '/examples/tabs': RouteRecordInfo<'/examples/tabs', '/examples/tabs', Record<never, never>, Record<never, never>>,
    '/examples/themes/Breeze': RouteRecordInfo<'/examples/themes/Breeze', '/examples/themes/Breeze', Record<never, never>, Record<never, never>>,
    '/examples/themes/Fluid': RouteRecordInfo<'/examples/themes/Fluid', '/examples/themes/Fluid', Record<never, never>, Record<never, never>>,
  }
}
